version: 2

sources:
  - name: brazilian_ecommerce
    description: "Raw data from Brazilian E-Commerce public dataset"
    database: ECOMMERCE
    schema: raw

    tables:
      - name: orders
        identifier: raw_olist_orders
        description: "Core table containing order information"
        columns:
          - name: order_id
            description: "Unique identifier for each order (primary key)"
          - name: customer_id
            description: "Identifier linking to customer information (foreign key)"
          - name: order_status
            description: "Current status of the order (e.g., delivered, canceled)"
          - name: order_purchase_timestamp
            description: "Timestamp when order was placed by customer"
          - name: order_approved_at
            description: "Timestamp when payment was approved"
          - name: order_delivered_carrier_date
            description: "Timestamp when order was handed to logistics carrier"
          - name: order_delivered_customer_date
            description: "Timestamp when order was delivered to customer"
          - name: order_estimated_delivery_date
            description: "Estimated delivery date provided at purchase time"

      - name: customers
        identifier: raw_olist_customers
        description: "Table containing customer demographic information"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer (primary key)"
          - name: customer_unique_id
            description: "Permanent customer identifier across multiple orders"
          - name: customer_zip_code_prefix
            description: "First 5 digits of customer's zip code"
          - name: customer_city
            description: "Customer's city of residence"
          - name: customer_state
            description: "Customer's state of residence (2-letter abbreviation)"

      - name: order_items
        identifier: raw_olist_order_items
        description: "Table containing individual items within orders"
        columns:
          - name: order_id
            description: "Identifier linking to parent order (foreign key)"
          - name: order_item_id
            description: "Sequential number identifying item position in order"
          - name: product_id
            description: "Identifier for purchased product (foreign key)"
          - name: seller_id
            description: "Identifier for product seller (foreign key)"
          - name: shipping_limit_date
            description: "Deadline for seller to deliver to logistics provider"
          - name: price
            description: "Unit price of the product"
          - name: freight_value
            description: "Shipping cost for the item"

      - name: order_payments
        identifier: raw_olist_order_payments
        description: "Table containing payment information for orders"
        columns:
          - name: order_id
            description: "Identifier linking to parent order (foreign key)"
          - name: payment_sequential
            description: "Sequence number for multiple payment methods"
          - name: payment_type
            description: "Payment method (e.g., credit card, voucher)"
          - name: payment_installments
            description: "Number of installments for payment"
          - name: payment_value
            description: "Total value of the payment"

      - name: order_reviews
        identifier: raw_olist_order_reviews
        description: "Table containing customer reviews of orders"
        columns:
          - name: review_id
            description: "Unique identifier for each review (primary key)"
          - name: order_id
            description: "Identifier linking to reviewed order (foreign key)"
          - name: review_score
            description: "Rating score from 1-5 given by customer"
          - name: review_comment_title
            description: "Title of the review comment"
          - name: review_comment_message
            description: "Detailed review comment text"
          - name: review_creation_date
            description: "Timestamp when review was created"
          - name: review_answer_timestamp
            description: "Timestamp when review was answered"

      - name: products
        identifier: raw_olist_products
        description: "Table containing product catalog information"
        columns:
          - name: product_id
            description: "Unique identifier for each product (primary key)"
          - name: product_category_name
            description: "Product category name in Portuguese"
          - name: product_name_length
            description: "Character count of product name"
          - name: product_description_length
            description: "Character count of product description"
          - name: product_photos_qty
            description: "Number of product photos available"
          - name: product_weight_g
            description: "Product weight in grams"
          - name: product_length_cm
            description: "Product length in centimeters"
          - name: product_height_cm
            description: "Product height in centimeters"
          - name: product_width_cm
            description: "Product width in centimeters"

      - name: product_categories
        identifier: raw_product_category_name
        description: "Translation table for product category names"
        columns:
          - name: product_category_name
            description: "Category name in Portuguese (primary key)"
          - name: product_category_name_english
            description: "English translation of category name"

      - name: sellers
        identifier: raw_olist_sellers
        description: "Table containing seller information"
        columns:
          - name: seller_id
            description: "Unique identifier for each seller (primary key)"
          - name: seller_zip_code_prefix
            description: "First 5 digits of seller's zip code"
          - name: seller_city
            description: "Seller's city location"
          - name: seller_state
            description: "Seller's state location (2-letter abbreviation)"

      - name: geolocation
        identifier: raw_olist_geolocation
        description: "Table containing geographic location data"
        columns:
          - name: geolocation_zip_code_prefix
            description: "First 5 digits of geographic zip code"
          - name: geolocation_lat
            description: "Latitude coordinate"
          - name: geolocation_lng
            description: "Longitude coordinate"
          - name: geolocation_city
            description: "City name for location"
          - name: geolocation_state
            description: "State name for location (2-letter abbreviation)"
